---
name: Setup Pipenv Virtual Environment

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Set up Python 3.9
      uses: actions/setup-python@main
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.9'
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64'
    - name: Install pipenv
      run: pip install pipenv
    - name: Install code dependencies
      run: pipenv install --dev