name: pr-checks

on:
  pull_request:
    branches:
      - main

jobs:
  pylint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Environment
        uses: ./.github/actions/setup-pipenv
      - name: Check lint issues
        run: pipenv run pylint src tests
  pycodestyle-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Environment
        uses: ./.github/actions/setup-pipenv
      - name: Check pycodestyle issues
        run: pipenv run pycodestyle
  pydocstyle-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Environment
        uses: ./.github/actions/setup-pipenv
      - name: Check pydocstyle issues
        run: pipenv run pydocstyle
  unittest-check:
    runs-on: ubuntu-latest
    needs: [pylint-check, pycodestyle-check, pydocstyle-check]
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Environment
        uses: ./.github/actions/setup-pipenv
      - name: Run unittests
        run: pipenv run pytest --cov=src --cov-fail-under=90 -vv --cov-report term-missing