name: pr-checks

on:
  pull_request:
    branches:
      - main

jobs:
  pylint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup-pipenv
      - name: Check lint issues
        run: pipenv run pylint src tests